# Generated by Django 4.1.4 on 2022-12-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('bean_from', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
